// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p11
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_FOO4DEFC_SCJSEU_H_
#define _TAO_IDL_FOO4DEFC_SCJSEU_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "manyfoolib_export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "tao/FloatSeqC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO ManyFooLib_Export

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace T4
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_T4_FLOATSEQ_CH_)
#define _T4_FLOATSEQ_CH_

  class FloatSeq;

  typedef
    ::TAO_FixedSeq_Var_T<
        FloatSeq
      >
    FloatSeq_var;

  typedef
    ::TAO_Seq_Out_T<
        FloatSeq
      >
    FloatSeq_out;

  class ManyFooLib_Export FloatSeq
    : public
        ::TAO::unbounded_value_sequence<
            ::CORBA::Float
          >
  {
  public:
    FloatSeq (void);
    FloatSeq ( ::CORBA::ULong max);
    FloatSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Float* buffer,
      ::CORBA::Boolean release = false);
    FloatSeq (const FloatSeq &);
    virtual ~FloatSeq (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef FloatSeq_var _var_type;
    typedef FloatSeq_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct Foo4;

  typedef
    ::TAO_Var_Var_T<
        Foo4
      >
    Foo4_var;

  typedef
    ::TAO_Out_T<
        Foo4
      >
    Foo4_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct ManyFooLib_Export Foo4
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef Foo4_var _var_type;
    typedef Foo4_out _out_type;
    
    ::CORBA::Long key;
    T4::FloatSeq values;
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module T4

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::T4::FloatSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::T4::FloatSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::T4::Foo4>
    : public
        Var_Size_Arg_Traits_T<
            ::T4::Foo4,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_T4_FloatSeq_H_
#define _TAO_CDR_OP_T4_FloatSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


ManyFooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const T4::FloatSeq &_tao_sequence);
ManyFooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    T4::FloatSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_T4_FloatSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

ManyFooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const T4::Foo4 &);
ManyFooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, T4::Foo4 &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "Foo4DefC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

