// $Id: Bug_2350_Regression.idl 14 2007-02-01 15:49:12Z mitza $

exception something
{
};

struct _user_ExceptionHolder
{
  long a;
};

interface Bug_2350_Regression
{
  void Bug_2350_Regression_excep(in _user_ExceptionHolder a)
         raises(something);
};
