// $Id: test.idl 2179 2013-05-28 22:16:51Z mesnierp $

#ifndef FOO_IDL
#define FOO_IDL

#include <Components.idl>

interface SetPoint
{
  void set(in double value);
};

interface Measurement
{
  double get();
};

porttype MCPort
{
  attribute double default_val;
  uses SetPoint control;
  uses Measurement meas;
};

component Foo
{
  mirrorport MCPort voltage;

};

#endif
