// $Id: Test.idl 2179 2013-05-28 22:16:51Z mesnierp $

module Test
{
  interface Client
  {
    oneway void reply (in string msg);
  };

  interface Server
  {
    void setup (in Client cli);

    oneway void request (in long sel);

    oneway void shutdown ();
  };

};

