// $Id: Obstack.cpp 2879 2016-09-23 18:29:04Z huangh $
#include "ace/Obstack.h"

ACE_BEGIN_VERSIONED_NAMESPACE_DECL

ACE_SINGLETON_TEMPLATE_INSTANTIATION(ACE_Obstack_T <char>;);

ACE_END_VERSIONED_NAMESPACE_DECL
