// $Id: Base.idl 2179 2013-05-28 22:16:51Z mesnierp $

#ifndef BASE_IDL
#define BASE_IDL

#include <Components.idl>

#pragma ciao lem "BaseE.idl"

module Inherited
{
  interface base_interface {
//     void do_base ();
//     attribute string str_base_interface;
  };
};

module Inherited
{
   component Base_comp
   {
      provides Inherited::base_interface prov_base;
      uses     Inherited::base_interface uses_base;
      attribute long base;
   };
};

#endif
