// $Id: Test.idl 2577 2015-06-19 21:57:06Z mesnierp $

// Test.idl

interface Messenger
{
  boolean send_message ( in    string user_name,
                         in    string subject,
                         inout string message );

};
