// $Id: Multiple_Inheritance.idl 14 2007-02-01 15:49:12Z mitza $

interface A
{
  string method1 ();
};

interface intB : A
{
  string method2 ();
};

interface C : A
{
  string method3 ();
};

interface D : intB, C
{
  string method4 ();
};

