// $Id: test_object.idl 14 2007-02-01 15:49:12Z mitza $

interface Test_Object
{
  // = TITLE
  //   This is a simple interface that tests the Naming Service.

  attribute short id;
  // This provides an easy way to differentiate objects if each
  // objects is served by a separate servant.
};
