// $Id: SetConnectorAttribute_Component.idl 2179 2013-05-28 22:16:51Z mesnierp $

/**
 * @file SetConnectorAttribute_Component.idl
 * @author Marcel Smit (msmit@remedy.nl)
 */

#ifndef COMPONENT_IDL
#define COMPONENT_IDL

#include "Connector/SetConnectorAttribute_Connector.idl"

module SetConnectorAttribute
{
  component SetConnectorAttributeComponent
  {
    port SetConnectorAttributeTestConnector::DDS_Write info_write;
  };
};

#endif
