// $Id: test.idl 1861 2011-08-31 16:18:08Z mesnierp $

interface Stopwatch
{
   void start ();
   // Start the Stop watch

   void stop ();
   // Stop the watch

  void shutdown ();
  // Shutdown the ORB
};
