FROM ubuntu:14.04.2
MAINTAINER hoyc.danny@gmail.com
RUN apt-get update
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get install node nodejs npm -y
RUN node -v
#RUN npm install -g node-red
