/* $Id: kokyu_config.h 14 2007-02-01 15:49:12Z mitza $ */
#ifndef KOKYU_CONFIG_H
#define KOKYU_CONFIG_H

#define CONFIG_DSTREAM_DSRT_DISPATCH
#define CONFIG_DSTREAM_DSRT_CV_DISPATCH
#define CONFIG_DSTREAM_DSRT_DIRECT_DISPATCH
#define CONFIG_DSTREAM_DSRT_DISPATCH_IMPL

#endif /* KOKYU_CONFIG_H */
