// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p11
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_FOODEFC_L6SB0M_H_
#define _TAO_IDL_FOODEFC_L6SB0M_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "foolib_export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Array_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/BD_String_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include "tao/Fixed_Array_Argument_T.h"
#include "tao/Var_Array_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "SharedTypesC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO FooLib_Export

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace Xyz
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFARRAYOFBOOLEAN_CH_)
#define _XYZ_SEQOFARRAYOFBOOLEAN_CH_

  class SeqOfArrayOfBoolean;

  typedef
    ::TAO_FixedSeq_Var_T<
        SeqOfArrayOfBoolean
      >
    SeqOfArrayOfBoolean_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfArrayOfBoolean
      >
    SeqOfArrayOfBoolean_out;

  class FooLib_Export SeqOfArrayOfBoolean
    : public
        ::TAO::bounded_array_sequence<
            ArrayOfBoolean,
            ArrayOfBoolean_slice,
            ArrayOfBoolean_tag,
            8
          >
  {
  public:
    SeqOfArrayOfBoolean (void);
    SeqOfArrayOfBoolean (
      ::CORBA::ULong length,
      ArrayOfBoolean* buffer,
      ::CORBA::Boolean release = false);
    SeqOfArrayOfBoolean (const SeqOfArrayOfBoolean &);
    virtual ~SeqOfArrayOfBoolean (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfArrayOfBoolean_var _var_type;
    typedef SeqOfArrayOfBoolean_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFARRAYOFSTRING_CH_)
#define _XYZ_SEQOFARRAYOFSTRING_CH_

  class SeqOfArrayOfString;

  typedef
    ::TAO_VarSeq_Var_T<
        SeqOfArrayOfString
      >
    SeqOfArrayOfString_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfArrayOfString
      >
    SeqOfArrayOfString_out;

  class FooLib_Export SeqOfArrayOfString
    : public
        ::TAO::bounded_array_sequence<
            ArrayOfString,
            ArrayOfString_slice,
            ArrayOfString_tag,
            8
          >
  {
  public:
    SeqOfArrayOfString (void);
    SeqOfArrayOfString (
      ::CORBA::ULong length,
      ArrayOfString* buffer,
      ::CORBA::Boolean release = false);
    SeqOfArrayOfString (const SeqOfArrayOfString &);
    virtual ~SeqOfArrayOfString (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfArrayOfString_var _var_type;
    typedef SeqOfArrayOfString_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFARRAYOFCHAR_CH_)
#define _XYZ_SEQOFARRAYOFCHAR_CH_

  class SeqOfArrayOfChar;

  typedef
    ::TAO_FixedSeq_Var_T<
        SeqOfArrayOfChar
      >
    SeqOfArrayOfChar_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfArrayOfChar
      >
    SeqOfArrayOfChar_out;

  class FooLib_Export SeqOfArrayOfChar
    : public
        ::TAO::bounded_array_sequence<
            ArrayOfChar,
            ArrayOfChar_slice,
            ArrayOfChar_tag,
            8
          >
  {
  public:
    SeqOfArrayOfChar (void);
    SeqOfArrayOfChar (
      ::CORBA::ULong length,
      ArrayOfChar* buffer,
      ::CORBA::Boolean release = false);
    SeqOfArrayOfChar (const SeqOfArrayOfChar &);
    virtual ~SeqOfArrayOfChar (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfArrayOfChar_var _var_type;
    typedef SeqOfArrayOfChar_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFARRAYOFOCTET_CH_)
#define _XYZ_SEQOFARRAYOFOCTET_CH_

  class SeqOfArrayOfOctet;

  typedef
    ::TAO_FixedSeq_Var_T<
        SeqOfArrayOfOctet
      >
    SeqOfArrayOfOctet_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfArrayOfOctet
      >
    SeqOfArrayOfOctet_out;

  class FooLib_Export SeqOfArrayOfOctet
    : public
        ::TAO::bounded_array_sequence<
            ArrayOfOctet,
            ArrayOfOctet_slice,
            ArrayOfOctet_tag,
            8
          >
  {
  public:
    SeqOfArrayOfOctet (void);
    SeqOfArrayOfOctet (
      ::CORBA::ULong length,
      ArrayOfOctet* buffer,
      ::CORBA::Boolean release = false);
    SeqOfArrayOfOctet (const SeqOfArrayOfOctet &);
    virtual ~SeqOfArrayOfOctet (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfArrayOfOctet_var _var_type;
    typedef SeqOfArrayOfOctet_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFARRAYOFLONG_CH_)
#define _XYZ_SEQOFARRAYOFLONG_CH_

  class SeqOfArrayOfLong;

  typedef
    ::TAO_FixedSeq_Var_T<
        SeqOfArrayOfLong
      >
    SeqOfArrayOfLong_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfArrayOfLong
      >
    SeqOfArrayOfLong_out;

  class FooLib_Export SeqOfArrayOfLong
    : public
        ::TAO::bounded_array_sequence<
            ArrayOfLong,
            ArrayOfLong_slice,
            ArrayOfLong_tag,
            8
          >
  {
  public:
    SeqOfArrayOfLong (void);
    SeqOfArrayOfLong (
      ::CORBA::ULong length,
      ArrayOfLong* buffer,
      ::CORBA::Boolean release = false);
    SeqOfArrayOfLong (const SeqOfArrayOfLong &);
    virtual ~SeqOfArrayOfLong (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfArrayOfLong_var _var_type;
    typedef SeqOfArrayOfLong_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFARRAYOFANENUM_CH_)
#define _XYZ_SEQOFARRAYOFANENUM_CH_

  class SeqOfArrayOfAnEnum;

  typedef
    ::TAO_FixedSeq_Var_T<
        SeqOfArrayOfAnEnum
      >
    SeqOfArrayOfAnEnum_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfArrayOfAnEnum
      >
    SeqOfArrayOfAnEnum_out;

  class FooLib_Export SeqOfArrayOfAnEnum
    : public
        ::TAO::bounded_array_sequence<
            ArrayOfAnEnum,
            ArrayOfAnEnum_slice,
            ArrayOfAnEnum_tag,
            8
          >
  {
  public:
    SeqOfArrayOfAnEnum (void);
    SeqOfArrayOfAnEnum (
      ::CORBA::ULong length,
      ArrayOfAnEnum* buffer,
      ::CORBA::Boolean release = false);
    SeqOfArrayOfAnEnum (const SeqOfArrayOfAnEnum &);
    virtual ~SeqOfArrayOfAnEnum (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfArrayOfAnEnum_var _var_type;
    typedef SeqOfArrayOfAnEnum_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ArrayOfBoolean ArrayOfArrayOfBoolean[7];
  typedef ArrayOfBoolean ArrayOfArrayOfBoolean_slice;
  struct ArrayOfArrayOfBoolean_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        ArrayOfArrayOfBoolean,
        ArrayOfArrayOfBoolean_slice,
        ArrayOfArrayOfBoolean_tag
      >
    ArrayOfArrayOfBoolean_var;

  typedef
    ArrayOfArrayOfBoolean
    ArrayOfArrayOfBoolean_out;

  typedef
    TAO_Array_Forany_T<
        ArrayOfArrayOfBoolean,
        ArrayOfArrayOfBoolean_slice,
        ArrayOfArrayOfBoolean_tag
      >
    ArrayOfArrayOfBoolean_forany;

  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfBoolean_slice *
  ArrayOfArrayOfBoolean_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfBoolean_free (
      ArrayOfArrayOfBoolean_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfBoolean_slice *
  ArrayOfArrayOfBoolean_dup (
      const ArrayOfArrayOfBoolean_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfBoolean_copy (
      ArrayOfArrayOfBoolean_slice *_tao_to,
      const ArrayOfArrayOfBoolean_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ArrayOfString ArrayOfArrayOfString[7];
  typedef ArrayOfString ArrayOfArrayOfString_slice;
  struct ArrayOfArrayOfString_tag {};
  

  typedef
    TAO_VarArray_Var_T<
        ArrayOfArrayOfString,
        ArrayOfArrayOfString_slice,
        ArrayOfArrayOfString_tag
      >
    ArrayOfArrayOfString_var;

  typedef
    TAO_Array_Out_T<
        ArrayOfArrayOfString,
        ArrayOfArrayOfString_var,
        ArrayOfArrayOfString_slice,
        ArrayOfArrayOfString_tag
      >
    ArrayOfArrayOfString_out;

  typedef
    TAO_Array_Forany_T<
        ArrayOfArrayOfString,
        ArrayOfArrayOfString_slice,
        ArrayOfArrayOfString_tag
      >
    ArrayOfArrayOfString_forany;

  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfString_slice *
  ArrayOfArrayOfString_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfString_free (
      ArrayOfArrayOfString_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfString_slice *
  ArrayOfArrayOfString_dup (
      const ArrayOfArrayOfString_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfString_copy (
      ArrayOfArrayOfString_slice *_tao_to,
      const ArrayOfArrayOfString_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ArrayOfChar ArrayOfArrayOfChar[7];
  typedef ArrayOfChar ArrayOfArrayOfChar_slice;
  struct ArrayOfArrayOfChar_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        ArrayOfArrayOfChar,
        ArrayOfArrayOfChar_slice,
        ArrayOfArrayOfChar_tag
      >
    ArrayOfArrayOfChar_var;

  typedef
    ArrayOfArrayOfChar
    ArrayOfArrayOfChar_out;

  typedef
    TAO_Array_Forany_T<
        ArrayOfArrayOfChar,
        ArrayOfArrayOfChar_slice,
        ArrayOfArrayOfChar_tag
      >
    ArrayOfArrayOfChar_forany;

  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfChar_slice *
  ArrayOfArrayOfChar_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfChar_free (
      ArrayOfArrayOfChar_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfChar_slice *
  ArrayOfArrayOfChar_dup (
      const ArrayOfArrayOfChar_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfChar_copy (
      ArrayOfArrayOfChar_slice *_tao_to,
      const ArrayOfArrayOfChar_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ArrayOfOctet ArrayOfArrayOfOctet[7];
  typedef ArrayOfOctet ArrayOfArrayOfOctet_slice;
  struct ArrayOfArrayOfOctet_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        ArrayOfArrayOfOctet,
        ArrayOfArrayOfOctet_slice,
        ArrayOfArrayOfOctet_tag
      >
    ArrayOfArrayOfOctet_var;

  typedef
    ArrayOfArrayOfOctet
    ArrayOfArrayOfOctet_out;

  typedef
    TAO_Array_Forany_T<
        ArrayOfArrayOfOctet,
        ArrayOfArrayOfOctet_slice,
        ArrayOfArrayOfOctet_tag
      >
    ArrayOfArrayOfOctet_forany;

  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfOctet_slice *
  ArrayOfArrayOfOctet_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfOctet_free (
      ArrayOfArrayOfOctet_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfOctet_slice *
  ArrayOfArrayOfOctet_dup (
      const ArrayOfArrayOfOctet_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfOctet_copy (
      ArrayOfArrayOfOctet_slice *_tao_to,
      const ArrayOfArrayOfOctet_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ArrayOfLong ArrayOfArrayOfLong[7];
  typedef ArrayOfLong ArrayOfArrayOfLong_slice;
  struct ArrayOfArrayOfLong_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        ArrayOfArrayOfLong,
        ArrayOfArrayOfLong_slice,
        ArrayOfArrayOfLong_tag
      >
    ArrayOfArrayOfLong_var;

  typedef
    ArrayOfArrayOfLong
    ArrayOfArrayOfLong_out;

  typedef
    TAO_Array_Forany_T<
        ArrayOfArrayOfLong,
        ArrayOfArrayOfLong_slice,
        ArrayOfArrayOfLong_tag
      >
    ArrayOfArrayOfLong_forany;

  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfLong_slice *
  ArrayOfArrayOfLong_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfLong_free (
      ArrayOfArrayOfLong_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfLong_slice *
  ArrayOfArrayOfLong_dup (
      const ArrayOfArrayOfLong_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfLong_copy (
      ArrayOfArrayOfLong_slice *_tao_to,
      const ArrayOfArrayOfLong_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ArrayOfAnEnum ArrayOfArrayOfAnEnum[7];
  typedef ArrayOfAnEnum ArrayOfArrayOfAnEnum_slice;
  struct ArrayOfArrayOfAnEnum_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        ArrayOfArrayOfAnEnum,
        ArrayOfArrayOfAnEnum_slice,
        ArrayOfArrayOfAnEnum_tag
      >
    ArrayOfArrayOfAnEnum_var;

  typedef
    ArrayOfArrayOfAnEnum
    ArrayOfArrayOfAnEnum_out;

  typedef
    TAO_Array_Forany_T<
        ArrayOfArrayOfAnEnum,
        ArrayOfArrayOfAnEnum_slice,
        ArrayOfArrayOfAnEnum_tag
      >
    ArrayOfArrayOfAnEnum_forany;

  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfAnEnum_slice *
  ArrayOfArrayOfAnEnum_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfAnEnum_free (
      ArrayOfArrayOfAnEnum_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS ArrayOfArrayOfAnEnum_slice *
  ArrayOfArrayOfAnEnum_dup (
      const ArrayOfArrayOfAnEnum_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfArrayOfAnEnum_copy (
      ArrayOfArrayOfAnEnum_slice *_tao_to,
      const ArrayOfArrayOfAnEnum_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructOfArrayOfArrayOfBoolean;

  typedef
    ::TAO_Fixed_Var_T<
        StructOfArrayOfArrayOfBoolean
      >
    StructOfArrayOfArrayOfBoolean_var;

  typedef
    StructOfArrayOfArrayOfBoolean &
    StructOfArrayOfArrayOfBoolean_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructOfArrayOfArrayOfBoolean
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructOfArrayOfArrayOfBoolean_var _var_type;
    typedef StructOfArrayOfArrayOfBoolean_out _out_type;
    
    Xyz::ArrayOfArrayOfBoolean f;
  };

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructOfArrayOfArrayOfString;

  typedef
    ::TAO_Var_Var_T<
        StructOfArrayOfArrayOfString
      >
    StructOfArrayOfArrayOfString_var;

  typedef
    ::TAO_Out_T<
        StructOfArrayOfArrayOfString
      >
    StructOfArrayOfArrayOfString_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructOfArrayOfArrayOfString
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructOfArrayOfArrayOfString_var _var_type;
    typedef StructOfArrayOfArrayOfString_out _out_type;
    
    Xyz::ArrayOfArrayOfString f;
  };

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructOfArrayOfArrayOfChar;

  typedef
    ::TAO_Fixed_Var_T<
        StructOfArrayOfArrayOfChar
      >
    StructOfArrayOfArrayOfChar_var;

  typedef
    StructOfArrayOfArrayOfChar &
    StructOfArrayOfArrayOfChar_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructOfArrayOfArrayOfChar
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructOfArrayOfArrayOfChar_var _var_type;
    typedef StructOfArrayOfArrayOfChar_out _out_type;
    
    Xyz::ArrayOfArrayOfChar f;
  };

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructOfArrayOfArrayOfOctet;

  typedef
    ::TAO_Fixed_Var_T<
        StructOfArrayOfArrayOfOctet
      >
    StructOfArrayOfArrayOfOctet_var;

  typedef
    StructOfArrayOfArrayOfOctet &
    StructOfArrayOfArrayOfOctet_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructOfArrayOfArrayOfOctet
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructOfArrayOfArrayOfOctet_var _var_type;
    typedef StructOfArrayOfArrayOfOctet_out _out_type;
    
    Xyz::ArrayOfArrayOfOctet f;
  };

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructOfArrayOfArrayOfLong;

  typedef
    ::TAO_Fixed_Var_T<
        StructOfArrayOfArrayOfLong
      >
    StructOfArrayOfArrayOfLong_var;

  typedef
    StructOfArrayOfArrayOfLong &
    StructOfArrayOfArrayOfLong_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructOfArrayOfArrayOfLong
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructOfArrayOfArrayOfLong_var _var_type;
    typedef StructOfArrayOfArrayOfLong_out _out_type;
    
    Xyz::ArrayOfArrayOfLong f;
  };

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructOfArrayOfArrayOfAnEnum;

  typedef
    ::TAO_Fixed_Var_T<
        StructOfArrayOfArrayOfAnEnum
      >
    StructOfArrayOfArrayOfAnEnum_var;

  typedef
    StructOfArrayOfArrayOfAnEnum &
    StructOfArrayOfArrayOfAnEnum_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructOfArrayOfArrayOfAnEnum
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructOfArrayOfArrayOfAnEnum_var _var_type;
    typedef StructOfArrayOfArrayOfAnEnum_out _out_type;
    
    Xyz::ArrayOfArrayOfAnEnum f;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFSEQOFBOOLEAN_CH_)
#define _XYZ_SEQOFSEQOFBOOLEAN_CH_

  class SeqOfSeqOfBoolean;

  typedef
    ::TAO_VarSeq_Var_T<
        SeqOfSeqOfBoolean
      >
    SeqOfSeqOfBoolean_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfSeqOfBoolean
      >
    SeqOfSeqOfBoolean_out;

  class FooLib_Export SeqOfSeqOfBoolean
    : public
        ::TAO::bounded_value_sequence<
            SeqOfBoolean,
            4
          >
  {
  public:
    SeqOfSeqOfBoolean (void);
    SeqOfSeqOfBoolean (
      ::CORBA::ULong length,
      SeqOfBoolean* buffer,
      ::CORBA::Boolean release = false);
    SeqOfSeqOfBoolean (const SeqOfSeqOfBoolean &);
    virtual ~SeqOfSeqOfBoolean (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfSeqOfBoolean_var _var_type;
    typedef SeqOfSeqOfBoolean_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFSEQOFSTRING_CH_)
#define _XYZ_SEQOFSEQOFSTRING_CH_

  class SeqOfSeqOfString;

  typedef
    ::TAO_VarSeq_Var_T<
        SeqOfSeqOfString
      >
    SeqOfSeqOfString_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfSeqOfString
      >
    SeqOfSeqOfString_out;

  class FooLib_Export SeqOfSeqOfString
    : public
        ::TAO::bounded_value_sequence<
            SeqOfString,
            4
          >
  {
  public:
    SeqOfSeqOfString (void);
    SeqOfSeqOfString (
      ::CORBA::ULong length,
      SeqOfString* buffer,
      ::CORBA::Boolean release = false);
    SeqOfSeqOfString (const SeqOfSeqOfString &);
    virtual ~SeqOfSeqOfString (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfSeqOfString_var _var_type;
    typedef SeqOfSeqOfString_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFSEQOFCHAR_CH_)
#define _XYZ_SEQOFSEQOFCHAR_CH_

  class SeqOfSeqOfChar;

  typedef
    ::TAO_VarSeq_Var_T<
        SeqOfSeqOfChar
      >
    SeqOfSeqOfChar_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfSeqOfChar
      >
    SeqOfSeqOfChar_out;

  class FooLib_Export SeqOfSeqOfChar
    : public
        ::TAO::bounded_value_sequence<
            SeqOfChar,
            4
          >
  {
  public:
    SeqOfSeqOfChar (void);
    SeqOfSeqOfChar (
      ::CORBA::ULong length,
      SeqOfChar* buffer,
      ::CORBA::Boolean release = false);
    SeqOfSeqOfChar (const SeqOfSeqOfChar &);
    virtual ~SeqOfSeqOfChar (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfSeqOfChar_var _var_type;
    typedef SeqOfSeqOfChar_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFSEQOFOCTET_CH_)
#define _XYZ_SEQOFSEQOFOCTET_CH_

  class SeqOfSeqOfOctet;

  typedef
    ::TAO_VarSeq_Var_T<
        SeqOfSeqOfOctet
      >
    SeqOfSeqOfOctet_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfSeqOfOctet
      >
    SeqOfSeqOfOctet_out;

  class FooLib_Export SeqOfSeqOfOctet
    : public
        ::TAO::bounded_value_sequence<
            SeqOfOctet,
            4
          >
  {
  public:
    SeqOfSeqOfOctet (void);
    SeqOfSeqOfOctet (
      ::CORBA::ULong length,
      SeqOfOctet* buffer,
      ::CORBA::Boolean release = false);
    SeqOfSeqOfOctet (const SeqOfSeqOfOctet &);
    virtual ~SeqOfSeqOfOctet (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfSeqOfOctet_var _var_type;
    typedef SeqOfSeqOfOctet_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFSEQOFLONG_CH_)
#define _XYZ_SEQOFSEQOFLONG_CH_

  class SeqOfSeqOfLong;

  typedef
    ::TAO_VarSeq_Var_T<
        SeqOfSeqOfLong
      >
    SeqOfSeqOfLong_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfSeqOfLong
      >
    SeqOfSeqOfLong_out;

  class FooLib_Export SeqOfSeqOfLong
    : public
        ::TAO::bounded_value_sequence<
            SeqOfLong,
            4
          >
  {
  public:
    SeqOfSeqOfLong (void);
    SeqOfSeqOfLong (
      ::CORBA::ULong length,
      SeqOfLong* buffer,
      ::CORBA::Boolean release = false);
    SeqOfSeqOfLong (const SeqOfSeqOfLong &);
    virtual ~SeqOfSeqOfLong (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfSeqOfLong_var _var_type;
    typedef SeqOfSeqOfLong_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFSEQOFANENUM_CH_)
#define _XYZ_SEQOFSEQOFANENUM_CH_

  class SeqOfSeqOfAnEnum;

  typedef
    ::TAO_VarSeq_Var_T<
        SeqOfSeqOfAnEnum
      >
    SeqOfSeqOfAnEnum_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfSeqOfAnEnum
      >
    SeqOfSeqOfAnEnum_out;

  class FooLib_Export SeqOfSeqOfAnEnum
    : public
        ::TAO::bounded_value_sequence<
            SeqOfAnEnum,
            4
          >
  {
  public:
    SeqOfSeqOfAnEnum (void);
    SeqOfSeqOfAnEnum (
      ::CORBA::ULong length,
      SeqOfAnEnum* buffer,
      ::CORBA::Boolean release = false);
    SeqOfSeqOfAnEnum (const SeqOfSeqOfAnEnum &);
    virtual ~SeqOfSeqOfAnEnum (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfSeqOfAnEnum_var _var_type;
    typedef SeqOfSeqOfAnEnum_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_typedef/typedef_ch.cpp:373

  typedef ::CORBA::Octet OctetTypedef;
  typedef ::CORBA::Octet_out OctetTypedef_out;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructOfSeqOfSeqOfLong;

  typedef
    ::TAO_Var_Var_T<
        StructOfSeqOfSeqOfLong
      >
    StructOfSeqOfSeqOfLong_var;

  typedef
    ::TAO_Out_T<
        StructOfSeqOfSeqOfLong
      >
    StructOfSeqOfSeqOfLong_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructOfSeqOfSeqOfLong
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructOfSeqOfSeqOfLong_var _var_type;
    typedef StructOfSeqOfSeqOfLong_out _out_type;
    
    Xyz::SeqOfSeqOfLong field;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typedef/typedef_ch.cpp:407

  typedef char * SevenStr;
  typedef ::CORBA::String_var SevenStr_var;
  typedef ::CORBA::String_out SevenStr_out;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct AStruct;

  typedef
    ::TAO_Var_Var_T<
        AStruct
      >
    AStruct_var;

  typedef
    ::TAO_Out_T<
        AStruct
      >
    AStruct_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export AStruct
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef AStruct_var _var_type;
    typedef AStruct_out _out_type;
    
    ::CORBA::Double f1;
    ::CORBA::Float f2;
    ::CORBA::Boolean f3;
    ::TAO::String_Manager f4;
    ::CORBA::Char f5;
    ::CORBA::Octet f6;
    Xyz::OctetTypedef f6a;
    ::CORBA::Long f7;
    Xyz::AnEnum f8;
    Xyz::ArrayOfBoolean f10;
    Xyz::ArrayOfString f11;
    Xyz::ArrayOfChar f12;
    Xyz::ArrayOfOctet f13;
    Xyz::ArrayOfLong f14;
    Xyz::ArrayOfAnEnum f15;
    Xyz::SeqOfBoolean f20;
    Xyz::SeqOfString f21;
    Xyz::SeqOfChar f22;
    Xyz::SeqOfOctet f23;
    Xyz::SeqOfLong f24;
    Xyz::SeqOfAnEnum f25;
    Xyz::ArrayOfSeqOfBoolean f30;
    Xyz::ArrayOfSeqOfString f31;
    Xyz::ArrayOfSeqOfChar f32;
    Xyz::ArrayOfSeqOfOctet f33;
    Xyz::ArrayOfSeqOfLong f34;
    Xyz::ArrayOfSeqOfAnEnum f35;
    Xyz::SeqOfArrayOfBoolean f40;
    Xyz::SeqOfArrayOfString f41;
    Xyz::SeqOfArrayOfChar f42;
    Xyz::SeqOfArrayOfOctet f43;
    Xyz::SeqOfArrayOfLong f44;
    Xyz::SeqOfArrayOfAnEnum f45;
    Xyz::ArrayOfArrayOfBoolean f50;
    Xyz::ArrayOfArrayOfString f51;
    Xyz::ArrayOfArrayOfChar f52;
    Xyz::ArrayOfArrayOfOctet f53;
    Xyz::ArrayOfArrayOfLong f54;
    Xyz::ArrayOfArrayOfAnEnum f55;
    Xyz::SeqOfSeqOfBoolean f60;
    Xyz::SeqOfSeqOfString f61;
    Xyz::SeqOfSeqOfChar f62;
    Xyz::SeqOfSeqOfOctet f63;
    Xyz::SeqOfSeqOfLong f64;
    Xyz::SeqOfSeqOfAnEnum f65;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFASTRUCT_CH_)
#define _XYZ_SEQOFASTRUCT_CH_

  class SeqOfAStruct;

  typedef
    ::TAO_VarSeq_Var_T<
        SeqOfAStruct
      >
    SeqOfAStruct_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfAStruct
      >
    SeqOfAStruct_out;

  class FooLib_Export SeqOfAStruct
    : public
        ::TAO::bounded_value_sequence<
            AStruct,
            2
          >
  {
  public:
    SeqOfAStruct (void);
    SeqOfAStruct (
      ::CORBA::ULong length,
      AStruct* buffer,
      ::CORBA::Boolean release = false);
    SeqOfAStruct (const SeqOfAStruct &);
    virtual ~SeqOfAStruct (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfAStruct_var _var_type;
    typedef SeqOfAStruct_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef AStruct ArrayOfAStruct[3];
  typedef AStruct ArrayOfAStruct_slice;
  struct ArrayOfAStruct_tag {};
  

  typedef
    TAO_VarArray_Var_T<
        ArrayOfAStruct,
        ArrayOfAStruct_slice,
        ArrayOfAStruct_tag
      >
    ArrayOfAStruct_var;

  typedef
    TAO_Array_Out_T<
        ArrayOfAStruct,
        ArrayOfAStruct_var,
        ArrayOfAStruct_slice,
        ArrayOfAStruct_tag
      >
    ArrayOfAStruct_out;

  typedef
    TAO_Array_Forany_T<
        ArrayOfAStruct,
        ArrayOfAStruct_slice,
        ArrayOfAStruct_tag
      >
    ArrayOfAStruct_forany;

  TAO_NAMESPACE_STORAGE_CLASS ArrayOfAStruct_slice *
  ArrayOfAStruct_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfAStruct_free (
      ArrayOfAStruct_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS ArrayOfAStruct_slice *
  ArrayOfAStruct_dup (
      const ArrayOfAStruct_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfAStruct_copy (
      ArrayOfAStruct_slice *_tao_to,
      const ArrayOfAStruct_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructContainingArrayOfAStruct;

  typedef
    ::TAO_Var_Var_T<
        StructContainingArrayOfAStruct
      >
    StructContainingArrayOfAStruct_var;

  typedef
    ::TAO_Out_T<
        StructContainingArrayOfAStruct
      >
    StructContainingArrayOfAStruct_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructContainingArrayOfAStruct
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructContainingArrayOfAStruct_var _var_type;
    typedef StructContainingArrayOfAStruct_out _out_type;
    
    Xyz::ArrayOfAStruct f1;
  };

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  class AUnion;

  typedef
    ::TAO_Var_Var_T<
        AUnion
      >
    AUnion_var;

  typedef
    ::TAO_Out_T<
        AUnion
      >
    AUnion_out;

  class FooLib_Export AUnion
  {
  public:
    AUnion (void);
    AUnion (const AUnion &);
    ~AUnion (void);

    AUnion &operator= (const AUnion &);

    // TAO_IDL - Generated from
    // be/be_visitor_union/discriminant_ch.cpp:70

    void _d (Xyz::AnEnum);
    Xyz::AnEnum _d (void) const;

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef AUnion_var _var_type;
    typedef AUnion_out _out_type;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:583

    void rv (char *);
    void rv (const char *);
    void rv (const ::CORBA::String_var&);
    const char *rv (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:659

    void gv (const Xyz::AStruct &);
    const Xyz::AStruct &gv (void) const;
    Xyz::AStruct &gv (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void bv (const Xyz::SeqOfLong &);
    const Xyz::SeqOfLong &bv (void) const;
    Xyz::SeqOfLong &bv (void);
  private:
    Xyz::AnEnum disc_;

    union
    {
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:477
      char *rv_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:522
      Xyz::AStruct *gv_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfLong *bv_;
    } u_;

    /// TAO extension - frees any allocated storage.
    void _reset (void);
  };

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  class BigUnion;

  typedef
    ::TAO_Var_Var_T<
        BigUnion
      >
    BigUnion_var;

  typedef
    ::TAO_Out_T<
        BigUnion
      >
    BigUnion_out;

  class FooLib_Export BigUnion
  {
  public:
    BigUnion (void);
    BigUnion (const BigUnion &);
    ~BigUnion (void);

    BigUnion &operator= (const BigUnion &);

    // TAO_IDL - Generated from
    // be/be_visitor_union/discriminant_ch.cpp:103

    void _d ( ::CORBA::Long);
    ::CORBA::Long _d (void) const;

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef BigUnion_var _var_type;
    typedef BigUnion_out _out_type;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:452

    void f1 ( ::CORBA::Double);
    ::CORBA::Double f1 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:452

    void f2 ( ::CORBA::Float);
    ::CORBA::Float f2 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:452

    void f3 ( ::CORBA::Boolean);
    ::CORBA::Boolean f3 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:583

    void f4 (char *);
    void f4 (const char *);
    void f4 (const ::CORBA::String_var&);
    const char *f4 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:452

    void f5 ( ::CORBA::Char);
    ::CORBA::Char f5 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:452

    void f6 ( ::CORBA::Octet);
    ::CORBA::Octet f6 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:452

    void f7 ( ::CORBA::Long);
    ::CORBA::Long f7 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:192

    void f8 (Xyz::AnEnum);
    Xyz::AnEnum f8 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f10 (Xyz::ArrayOfBoolean);
    Xyz::ArrayOfBoolean_slice * f10 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f11 (Xyz::ArrayOfString);
    Xyz::ArrayOfString_slice * f11 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f12 (Xyz::ArrayOfChar);
    Xyz::ArrayOfChar_slice * f12 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f13 (Xyz::ArrayOfOctet);
    Xyz::ArrayOfOctet_slice * f13 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f14 (Xyz::ArrayOfLong);
    Xyz::ArrayOfLong_slice * f14 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f15 (Xyz::ArrayOfAnEnum);
    Xyz::ArrayOfAnEnum_slice * f15 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f20 (const Xyz::SeqOfBoolean &);
    const Xyz::SeqOfBoolean &f20 (void) const;
    Xyz::SeqOfBoolean &f20 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f21 (const Xyz::SeqOfString &);
    const Xyz::SeqOfString &f21 (void) const;
    Xyz::SeqOfString &f21 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f22 (const Xyz::SeqOfChar &);
    const Xyz::SeqOfChar &f22 (void) const;
    Xyz::SeqOfChar &f22 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f23 (const Xyz::SeqOfOctet &);
    const Xyz::SeqOfOctet &f23 (void) const;
    Xyz::SeqOfOctet &f23 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f24 (const Xyz::SeqOfLong &);
    const Xyz::SeqOfLong &f24 (void) const;
    Xyz::SeqOfLong &f24 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f25 (const Xyz::SeqOfAnEnum &);
    const Xyz::SeqOfAnEnum &f25 (void) const;
    Xyz::SeqOfAnEnum &f25 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f30 (Xyz::ArrayOfSeqOfBoolean);
    Xyz::ArrayOfSeqOfBoolean_slice * f30 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f31 (Xyz::ArrayOfSeqOfString);
    Xyz::ArrayOfSeqOfString_slice * f31 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f32 (Xyz::ArrayOfSeqOfChar);
    Xyz::ArrayOfSeqOfChar_slice * f32 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f33 (Xyz::ArrayOfSeqOfOctet);
    Xyz::ArrayOfSeqOfOctet_slice * f33 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f34 (Xyz::ArrayOfSeqOfLong);
    Xyz::ArrayOfSeqOfLong_slice * f34 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f35 (Xyz::ArrayOfSeqOfAnEnum);
    Xyz::ArrayOfSeqOfAnEnum_slice * f35 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f40 (const Xyz::SeqOfArrayOfBoolean &);
    const Xyz::SeqOfArrayOfBoolean &f40 (void) const;
    Xyz::SeqOfArrayOfBoolean &f40 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f41 (const Xyz::SeqOfArrayOfString &);
    const Xyz::SeqOfArrayOfString &f41 (void) const;
    Xyz::SeqOfArrayOfString &f41 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f42 (const Xyz::SeqOfArrayOfChar &);
    const Xyz::SeqOfArrayOfChar &f42 (void) const;
    Xyz::SeqOfArrayOfChar &f42 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f43 (const Xyz::SeqOfArrayOfOctet &);
    const Xyz::SeqOfArrayOfOctet &f43 (void) const;
    Xyz::SeqOfArrayOfOctet &f43 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f44 (const Xyz::SeqOfArrayOfLong &);
    const Xyz::SeqOfArrayOfLong &f44 (void) const;
    Xyz::SeqOfArrayOfLong &f44 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f45 (const Xyz::SeqOfArrayOfAnEnum &);
    const Xyz::SeqOfArrayOfAnEnum &f45 (void) const;
    Xyz::SeqOfArrayOfAnEnum &f45 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f50 (Xyz::ArrayOfArrayOfBoolean);
    Xyz::ArrayOfArrayOfBoolean_slice * f50 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f51 (Xyz::ArrayOfArrayOfString);
    Xyz::ArrayOfArrayOfString_slice * f51 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f52 (Xyz::ArrayOfArrayOfChar);
    Xyz::ArrayOfArrayOfChar_slice * f52 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f53 (Xyz::ArrayOfArrayOfOctet);
    Xyz::ArrayOfArrayOfOctet_slice * f53 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f54 (Xyz::ArrayOfArrayOfLong);
    Xyz::ArrayOfArrayOfLong_slice * f54 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void f55 (Xyz::ArrayOfArrayOfAnEnum);
    Xyz::ArrayOfArrayOfAnEnum_slice * f55 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f60 (const Xyz::SeqOfSeqOfBoolean &);
    const Xyz::SeqOfSeqOfBoolean &f60 (void) const;
    Xyz::SeqOfSeqOfBoolean &f60 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f61 (const Xyz::SeqOfSeqOfString &);
    const Xyz::SeqOfSeqOfString &f61 (void) const;
    Xyz::SeqOfSeqOfString &f61 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f62 (const Xyz::SeqOfSeqOfChar &);
    const Xyz::SeqOfSeqOfChar &f62 (void) const;
    Xyz::SeqOfSeqOfChar &f62 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f63 (const Xyz::SeqOfSeqOfOctet &);
    const Xyz::SeqOfSeqOfOctet &f63 (void) const;
    Xyz::SeqOfSeqOfOctet &f63 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f64 (const Xyz::SeqOfSeqOfLong &);
    const Xyz::SeqOfSeqOfLong &f64 (void) const;
    Xyz::SeqOfSeqOfLong &f64 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f65 (const Xyz::SeqOfSeqOfAnEnum &);
    const Xyz::SeqOfSeqOfAnEnum &f65 (void) const;
    Xyz::SeqOfSeqOfAnEnum &f65 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:452

    void f6a ( Xyz::OctetTypedef);
    Xyz::OctetTypedef f6a (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:659

    void f90 (const Xyz::AStruct &);
    const Xyz::AStruct &f90 (void) const;
    Xyz::AStruct &f90 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:551

    void f91 (const Xyz::SeqOfAStruct &);
    const Xyz::SeqOfAStruct &f91 (void) const;
    Xyz::SeqOfAStruct &f91 (void);

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:129

    void v92 (Xyz::ArrayOfAStruct);
    Xyz::ArrayOfAStruct_slice * v92 (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union_branch/public_ch.cpp:452

    void ld ( ::CORBA::LongDouble);
    ::CORBA::LongDouble ld (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_union/union_ch.cpp:124

    void _default (void);
  private:
    ::CORBA::Long disc_;

    union
    {
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:380
      ::CORBA::Double f1_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:380
      ::CORBA::Float f2_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:380
      ::CORBA::Boolean f3_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:477
      char *f4_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:380
      ::CORBA::Char f5_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:380
      ::CORBA::Octet f6_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:380
      ::CORBA::Long f7_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:143
      Xyz::AnEnum f8_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfBoolean_slice *f10_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfString_slice *f11_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfChar_slice *f12_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfOctet_slice *f13_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfLong_slice *f14_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfAnEnum_slice *f15_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfBoolean *f20_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfString *f21_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfChar *f22_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfOctet *f23_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfLong *f24_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfAnEnum *f25_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfSeqOfBoolean_slice *f30_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfSeqOfString_slice *f31_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfSeqOfChar_slice *f32_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfSeqOfOctet_slice *f33_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfSeqOfLong_slice *f34_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfSeqOfAnEnum_slice *f35_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfArrayOfBoolean *f40_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfArrayOfString *f41_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfArrayOfChar *f42_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfArrayOfOctet *f43_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfArrayOfLong *f44_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfArrayOfAnEnum *f45_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfArrayOfBoolean_slice *f50_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfArrayOfString_slice *f51_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfArrayOfChar_slice *f52_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfArrayOfOctet_slice *f53_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfArrayOfLong_slice *f54_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfArrayOfAnEnum_slice *f55_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfSeqOfBoolean *f60_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfSeqOfString *f61_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfSeqOfChar *f62_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfSeqOfOctet *f63_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfSeqOfLong *f64_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfSeqOfAnEnum *f65_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:380
      Xyz::OctetTypedef f6a_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:522
      Xyz::AStruct *f90_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:447
      Xyz::SeqOfAStruct *f91_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:93
      Xyz::ArrayOfAStruct_slice *v92_;
      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/private_ch.cpp:380
      ::CORBA::LongDouble ld_;
    } u_;

    /// TAO extension - frees any allocated storage.
    void _reset (void);
  };

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructAUnion;

  typedef
    ::TAO_Var_Var_T<
        StructAUnion
      >
    StructAUnion_var;

  typedef
    ::TAO_Out_T<
        StructAUnion
      >
    StructAUnion_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructAUnion
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructAUnion_var _var_type;
    typedef StructAUnion_out _out_type;
    
    

    Xyz::AUnion sau_f1;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_SEQOFAUNION_CH_)
#define _XYZ_SEQOFAUNION_CH_

  class SeqOfAUnion;

  typedef
    ::TAO_VarSeq_Var_T<
        SeqOfAUnion
      >
    SeqOfAUnion_var;

  typedef
    ::TAO_Seq_Out_T<
        SeqOfAUnion
      >
    SeqOfAUnion_out;

  class FooLib_Export SeqOfAUnion
    : public
        ::TAO::bounded_value_sequence<
            AUnion,
            3
          >
  {
  public:
    SeqOfAUnion (void);
    SeqOfAUnion (
      ::CORBA::ULong length,
      AUnion* buffer,
      ::CORBA::Boolean release = false);
    SeqOfAUnion (const SeqOfAUnion &);
    virtual ~SeqOfAUnion (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SeqOfAUnion_var _var_type;
    typedef SeqOfAUnion_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_ASTRUCTSEQ_CH_)
#define _XYZ_ASTRUCTSEQ_CH_

  class AStructSeq;

  typedef
    ::TAO_VarSeq_Var_T<
        AStructSeq
      >
    AStructSeq_var;

  typedef
    ::TAO_Seq_Out_T<
        AStructSeq
      >
    AStructSeq_out;

  class FooLib_Export AStructSeq
    : public
        ::TAO::bounded_value_sequence<
            AStruct,
            3
          >
  {
  public:
    AStructSeq (void);
    AStructSeq (
      ::CORBA::ULong length,
      AStruct* buffer,
      ::CORBA::Boolean release = false);
    AStructSeq (const AStructSeq &);
    virtual ~AStructSeq (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef AStructSeq_var _var_type;
    typedef AStructSeq_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef AStructSeq ArrayOfAStructSeq[3];
  typedef AStructSeq ArrayOfAStructSeq_slice;
  struct ArrayOfAStructSeq_tag {};
  

  typedef
    TAO_VarArray_Var_T<
        ArrayOfAStructSeq,
        ArrayOfAStructSeq_slice,
        ArrayOfAStructSeq_tag
      >
    ArrayOfAStructSeq_var;

  typedef
    TAO_Array_Out_T<
        ArrayOfAStructSeq,
        ArrayOfAStructSeq_var,
        ArrayOfAStructSeq_slice,
        ArrayOfAStructSeq_tag
      >
    ArrayOfAStructSeq_out;

  typedef
    TAO_Array_Forany_T<
        ArrayOfAStructSeq,
        ArrayOfAStructSeq_slice,
        ArrayOfAStructSeq_tag
      >
    ArrayOfAStructSeq_forany;

  TAO_NAMESPACE_STORAGE_CLASS ArrayOfAStructSeq_slice *
  ArrayOfAStructSeq_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfAStructSeq_free (
      ArrayOfAStructSeq_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS ArrayOfAStructSeq_slice *
  ArrayOfAStructSeq_dup (
      const ArrayOfAStructSeq_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  ArrayOfAStructSeq_copy (
      ArrayOfAStructSeq_slice *_tao_to,
      const ArrayOfAStructSeq_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct StructContainingArrayOfAStructSeq;

  typedef
    ::TAO_Var_Var_T<
        StructContainingArrayOfAStructSeq
      >
    StructContainingArrayOfAStructSeq_var;

  typedef
    ::TAO_Out_T<
        StructContainingArrayOfAStructSeq
      >
    StructContainingArrayOfAStructSeq_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export StructContainingArrayOfAStructSeq
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef StructContainingArrayOfAStructSeq_var _var_type;
    typedef StructContainingArrayOfAStructSeq_out _out_type;
    
    Xyz::ArrayOfAStructSeq f1;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_XYZ_BIGUNIONSEQ_CH_)
#define _XYZ_BIGUNIONSEQ_CH_

  class BigUnionSeq;

  typedef
    ::TAO_VarSeq_Var_T<
        BigUnionSeq
      >
    BigUnionSeq_var;

  typedef
    ::TAO_Seq_Out_T<
        BigUnionSeq
      >
    BigUnionSeq_out;

  class FooLib_Export BigUnionSeq
    : public
        ::TAO::unbounded_value_sequence<
            BigUnion
          >
  {
  public:
    BigUnionSeq (void);
    BigUnionSeq ( ::CORBA::ULong max);
    BigUnionSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      BigUnion* buffer,
      ::CORBA::Boolean release = false);
    BigUnionSeq (const BigUnionSeq &);
    virtual ~BigUnionSeq (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef BigUnionSeq_var _var_type;
    typedef BigUnionSeq_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ::CORBA::Octet OctetArray[3];
  typedef ::CORBA::Octet OctetArray_slice;
  struct OctetArray_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        OctetArray,
        OctetArray_slice,
        OctetArray_tag
      >
    OctetArray_var;

  typedef
    OctetArray
    OctetArray_out;

  typedef
    TAO_Array_Forany_T<
        OctetArray,
        OctetArray_slice,
        OctetArray_tag
      >
    OctetArray_forany;

  TAO_NAMESPACE_STORAGE_CLASS OctetArray_slice *
  OctetArray_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  OctetArray_free (
      OctetArray_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS OctetArray_slice *
  OctetArray_dup (
      const OctetArray_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  OctetArray_copy (
      OctetArray_slice *_tao_to,
      const OctetArray_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct Foo;

  typedef
    ::TAO_Var_Var_T<
        Foo
      >
    Foo_var;

  typedef
    ::TAO_Out_T<
        Foo
      >
    Foo_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct FooLib_Export Foo
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef Foo_var _var_type;
    typedef Foo_out _out_type;
    
    ::CORBA::Long key;
    ::CORBA::Octet octer;
    Xyz::OctetTypedef theOctetTypedef;
    Xyz::AnEnum xcolor;
    Xyz::OctetArray ooo;
    ::TAO::String_Manager theString;
    Xyz::AStruct thestruct;
    Xyz::AStructSeq theStructSeq;
    Xyz::ArrayOfAStruct structArray;
    

    Xyz::AUnion theUnion;
    Xyz::SeqOfAUnion theSeqOfUnion;
    

    Xyz::BigUnion theBigUnion;
    Xyz::BigUnionSeq theSeqOfBitUnion;
    ::CORBA::Float x;
    ::CORBA::Float y;
    ::CORBA::WChar theWChar;
    ::TAO::WString_Manager theWString;
    ::CORBA::LongDouble theLongDouble;
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module Xyz

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfArrayOfBoolean>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfArrayOfBoolean,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfArrayOfString>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfArrayOfString,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfArrayOfChar>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfArrayOfChar,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfArrayOfOctet>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfArrayOfOctet,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfArrayOfLong>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfArrayOfLong,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfArrayOfAnEnum>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfArrayOfAnEnum,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class Arg_Traits< ::Xyz::ArrayOfArrayOfBoolean_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::Xyz::ArrayOfArrayOfBoolean_var,
            ::Xyz::ArrayOfArrayOfBoolean_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class Arg_Traits< ::Xyz::ArrayOfArrayOfString_tag>
    : public
        Var_Array_Arg_Traits_T<
            ::Xyz::ArrayOfArrayOfString_out,
            ::Xyz::ArrayOfArrayOfString_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class Arg_Traits< ::Xyz::ArrayOfArrayOfChar_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::Xyz::ArrayOfArrayOfChar_var,
            ::Xyz::ArrayOfArrayOfChar_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class Arg_Traits< ::Xyz::ArrayOfArrayOfOctet_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::Xyz::ArrayOfArrayOfOctet_var,
            ::Xyz::ArrayOfArrayOfOctet_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class Arg_Traits< ::Xyz::ArrayOfArrayOfLong_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::Xyz::ArrayOfArrayOfLong_var,
            ::Xyz::ArrayOfArrayOfLong_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class Arg_Traits< ::Xyz::ArrayOfArrayOfAnEnum_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::Xyz::ArrayOfArrayOfAnEnum_var,
            ::Xyz::ArrayOfArrayOfAnEnum_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructOfArrayOfArrayOfBoolean>
    : public
        Fixed_Size_Arg_Traits_T<
            ::Xyz::StructOfArrayOfArrayOfBoolean,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructOfArrayOfArrayOfString>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::StructOfArrayOfArrayOfString,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructOfArrayOfArrayOfChar>
    : public
        Fixed_Size_Arg_Traits_T<
            ::Xyz::StructOfArrayOfArrayOfChar,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructOfArrayOfArrayOfOctet>
    : public
        Fixed_Size_Arg_Traits_T<
            ::Xyz::StructOfArrayOfArrayOfOctet,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructOfArrayOfArrayOfLong>
    : public
        Fixed_Size_Arg_Traits_T<
            ::Xyz::StructOfArrayOfArrayOfLong,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructOfArrayOfArrayOfAnEnum>
    : public
        Fixed_Size_Arg_Traits_T<
            ::Xyz::StructOfArrayOfArrayOfAnEnum,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfSeqOfBoolean>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfSeqOfBoolean,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfSeqOfString>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfSeqOfString,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfSeqOfChar>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfSeqOfChar,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfSeqOfOctet>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfSeqOfOctet,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfSeqOfLong>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfSeqOfLong,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfSeqOfAnEnum>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfSeqOfAnEnum,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructOfSeqOfSeqOfLong>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::StructOfSeqOfSeqOfLong,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_SEVENSTR7__ARG_TRAITS_)
#define _SEVENSTR7__ARG_TRAITS_

  struct SevenStr_7 {};

  template<>
  class Arg_Traits<SevenStr_7>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            7,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::AStruct>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::AStruct,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfAStruct>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfAStruct,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class Arg_Traits< ::Xyz::ArrayOfAStruct_tag>
    : public
        Var_Array_Arg_Traits_T<
            ::Xyz::ArrayOfAStruct_out,
            ::Xyz::ArrayOfAStruct_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructContainingArrayOfAStruct>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::StructContainingArrayOfAStruct,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:1058

  template<>
  class Arg_Traits< ::Xyz::AUnion>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::AUnion,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:1058

  template<>
  class Arg_Traits< ::Xyz::BigUnion>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::BigUnion,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructAUnion>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::StructAUnion,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::SeqOfAUnion>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::SeqOfAUnion,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::AStructSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::AStructSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class Arg_Traits< ::Xyz::ArrayOfAStructSeq_tag>
    : public
        Var_Array_Arg_Traits_T<
            ::Xyz::ArrayOfAStructSeq_out,
            ::Xyz::ArrayOfAStructSeq_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::StructContainingArrayOfAStructSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::StructContainingArrayOfAStructSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::Xyz::BigUnionSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::BigUnionSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class Arg_Traits< ::Xyz::OctetArray_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::Xyz::OctetArray_var,
            ::Xyz::OctetArray_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Xyz::Foo>
    : public
        Var_Size_Arg_Traits_T<
            ::Xyz::Foo,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
  template<>
  struct FooLib_Export Array_Traits<
      Xyz::ArrayOfArrayOfBoolean_forany
    >
  {
    static void free (
        Xyz::ArrayOfArrayOfBoolean_slice * _tao_slice);
    static Xyz::ArrayOfArrayOfBoolean_slice * dup (
        const Xyz::ArrayOfArrayOfBoolean_slice * _tao_slice);
    static void copy (
        Xyz::ArrayOfArrayOfBoolean_slice * _tao_to,
        const Xyz::ArrayOfArrayOfBoolean_slice * _tao_from);
    static Xyz::ArrayOfArrayOfBoolean_slice * alloc (void);
    static void zero (
        Xyz::ArrayOfArrayOfBoolean_slice * _tao_slice);
  };
  template<>
  struct FooLib_Export Array_Traits<
      Xyz::ArrayOfArrayOfString_forany
    >
  {
    static void free (
        Xyz::ArrayOfArrayOfString_slice * _tao_slice);
    static Xyz::ArrayOfArrayOfString_slice * dup (
        const Xyz::ArrayOfArrayOfString_slice * _tao_slice);
    static void copy (
        Xyz::ArrayOfArrayOfString_slice * _tao_to,
        const Xyz::ArrayOfArrayOfString_slice * _tao_from);
    static Xyz::ArrayOfArrayOfString_slice * alloc (void);
    static void zero (
        Xyz::ArrayOfArrayOfString_slice * _tao_slice);
  };
  template<>
  struct FooLib_Export Array_Traits<
      Xyz::ArrayOfArrayOfChar_forany
    >
  {
    static void free (
        Xyz::ArrayOfArrayOfChar_slice * _tao_slice);
    static Xyz::ArrayOfArrayOfChar_slice * dup (
        const Xyz::ArrayOfArrayOfChar_slice * _tao_slice);
    static void copy (
        Xyz::ArrayOfArrayOfChar_slice * _tao_to,
        const Xyz::ArrayOfArrayOfChar_slice * _tao_from);
    static Xyz::ArrayOfArrayOfChar_slice * alloc (void);
    static void zero (
        Xyz::ArrayOfArrayOfChar_slice * _tao_slice);
  };
  template<>
  struct FooLib_Export Array_Traits<
      Xyz::ArrayOfArrayOfOctet_forany
    >
  {
    static void free (
        Xyz::ArrayOfArrayOfOctet_slice * _tao_slice);
    static Xyz::ArrayOfArrayOfOctet_slice * dup (
        const Xyz::ArrayOfArrayOfOctet_slice * _tao_slice);
    static void copy (
        Xyz::ArrayOfArrayOfOctet_slice * _tao_to,
        const Xyz::ArrayOfArrayOfOctet_slice * _tao_from);
    static Xyz::ArrayOfArrayOfOctet_slice * alloc (void);
    static void zero (
        Xyz::ArrayOfArrayOfOctet_slice * _tao_slice);
  };
  template<>
  struct FooLib_Export Array_Traits<
      Xyz::ArrayOfArrayOfLong_forany
    >
  {
    static void free (
        Xyz::ArrayOfArrayOfLong_slice * _tao_slice);
    static Xyz::ArrayOfArrayOfLong_slice * dup (
        const Xyz::ArrayOfArrayOfLong_slice * _tao_slice);
    static void copy (
        Xyz::ArrayOfArrayOfLong_slice * _tao_to,
        const Xyz::ArrayOfArrayOfLong_slice * _tao_from);
    static Xyz::ArrayOfArrayOfLong_slice * alloc (void);
    static void zero (
        Xyz::ArrayOfArrayOfLong_slice * _tao_slice);
  };
  template<>
  struct FooLib_Export Array_Traits<
      Xyz::ArrayOfArrayOfAnEnum_forany
    >
  {
    static void free (
        Xyz::ArrayOfArrayOfAnEnum_slice * _tao_slice);
    static Xyz::ArrayOfArrayOfAnEnum_slice * dup (
        const Xyz::ArrayOfArrayOfAnEnum_slice * _tao_slice);
    static void copy (
        Xyz::ArrayOfArrayOfAnEnum_slice * _tao_to,
        const Xyz::ArrayOfArrayOfAnEnum_slice * _tao_from);
    static Xyz::ArrayOfArrayOfAnEnum_slice * alloc (void);
    static void zero (
        Xyz::ArrayOfArrayOfAnEnum_slice * _tao_slice);
  };
  template<>
  struct FooLib_Export Array_Traits<
      Xyz::ArrayOfAStruct_forany
    >
  {
    static void free (
        Xyz::ArrayOfAStruct_slice * _tao_slice);
    static Xyz::ArrayOfAStruct_slice * dup (
        const Xyz::ArrayOfAStruct_slice * _tao_slice);
    static void copy (
        Xyz::ArrayOfAStruct_slice * _tao_to,
        const Xyz::ArrayOfAStruct_slice * _tao_from);
    static Xyz::ArrayOfAStruct_slice * alloc (void);
    static void zero (
        Xyz::ArrayOfAStruct_slice * _tao_slice);
  };
  template<>
  struct FooLib_Export Array_Traits<
      Xyz::ArrayOfAStructSeq_forany
    >
  {
    static void free (
        Xyz::ArrayOfAStructSeq_slice * _tao_slice);
    static Xyz::ArrayOfAStructSeq_slice * dup (
        const Xyz::ArrayOfAStructSeq_slice * _tao_slice);
    static void copy (
        Xyz::ArrayOfAStructSeq_slice * _tao_to,
        const Xyz::ArrayOfAStructSeq_slice * _tao_from);
    static Xyz::ArrayOfAStructSeq_slice * alloc (void);
    static void zero (
        Xyz::ArrayOfAStructSeq_slice * _tao_slice);
  };
  template<>
  struct FooLib_Export Array_Traits<
      Xyz::OctetArray_forany
    >
  {
    static void free (
        Xyz::OctetArray_slice * _tao_slice);
    static Xyz::OctetArray_slice * dup (
        const Xyz::OctetArray_slice * _tao_slice);
    static void copy (
        Xyz::OctetArray_slice * _tao_to,
        const Xyz::OctetArray_slice * _tao_from);
    static Xyz::OctetArray_slice * alloc (void);
    static void zero (
        Xyz::OctetArray_slice * _tao_slice);
  };
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfArrayOfBoolean_H_
#define _TAO_CDR_OP_Xyz_SeqOfArrayOfBoolean_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfArrayOfBoolean &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfArrayOfBoolean &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfArrayOfBoolean_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfArrayOfString_H_
#define _TAO_CDR_OP_Xyz_SeqOfArrayOfString_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfArrayOfString &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfArrayOfString &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfArrayOfString_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfArrayOfChar_H_
#define _TAO_CDR_OP_Xyz_SeqOfArrayOfChar_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfArrayOfChar &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfArrayOfChar &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfArrayOfChar_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfArrayOfOctet_H_
#define _TAO_CDR_OP_Xyz_SeqOfArrayOfOctet_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfArrayOfOctet &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfArrayOfOctet &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfArrayOfOctet_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfArrayOfLong_H_
#define _TAO_CDR_OP_Xyz_SeqOfArrayOfLong_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfArrayOfLong &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfArrayOfLong &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfArrayOfLong_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfArrayOfAnEnum_H_
#define _TAO_CDR_OP_Xyz_SeqOfArrayOfAnEnum_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfArrayOfAnEnum &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfArrayOfAnEnum &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfArrayOfAnEnum_H_ */

// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Xyz::ArrayOfArrayOfBoolean_forany &_tao_array);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::ArrayOfArrayOfBoolean_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Xyz::ArrayOfArrayOfString_forany &_tao_array);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::ArrayOfArrayOfString_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Xyz::ArrayOfArrayOfChar_forany &_tao_array);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::ArrayOfArrayOfChar_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Xyz::ArrayOfArrayOfOctet_forany &_tao_array);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::ArrayOfArrayOfOctet_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Xyz::ArrayOfArrayOfLong_forany &_tao_array);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::ArrayOfArrayOfLong_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Xyz::ArrayOfArrayOfAnEnum_forany &_tao_array);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::ArrayOfArrayOfAnEnum_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructOfArrayOfArrayOfBoolean &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructOfArrayOfArrayOfBoolean &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructOfArrayOfArrayOfString &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructOfArrayOfArrayOfString &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructOfArrayOfArrayOfChar &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructOfArrayOfArrayOfChar &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructOfArrayOfArrayOfOctet &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructOfArrayOfArrayOfOctet &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructOfArrayOfArrayOfLong &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructOfArrayOfArrayOfLong &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructOfArrayOfArrayOfAnEnum &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructOfArrayOfArrayOfAnEnum &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfSeqOfBoolean_H_
#define _TAO_CDR_OP_Xyz_SeqOfSeqOfBoolean_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfSeqOfBoolean &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfSeqOfBoolean &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfSeqOfBoolean_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfSeqOfString_H_
#define _TAO_CDR_OP_Xyz_SeqOfSeqOfString_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfSeqOfString &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfSeqOfString &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfSeqOfString_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfSeqOfChar_H_
#define _TAO_CDR_OP_Xyz_SeqOfSeqOfChar_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfSeqOfChar &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfSeqOfChar &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfSeqOfChar_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfSeqOfOctet_H_
#define _TAO_CDR_OP_Xyz_SeqOfSeqOfOctet_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfSeqOfOctet &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfSeqOfOctet &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfSeqOfOctet_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfSeqOfLong_H_
#define _TAO_CDR_OP_Xyz_SeqOfSeqOfLong_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfSeqOfLong &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfSeqOfLong &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfSeqOfLong_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfSeqOfAnEnum_H_
#define _TAO_CDR_OP_Xyz_SeqOfSeqOfAnEnum_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfSeqOfAnEnum &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfSeqOfAnEnum &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfSeqOfAnEnum_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructOfSeqOfSeqOfLong &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructOfSeqOfSeqOfLong &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::AStruct &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::AStruct &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfAStruct_H_
#define _TAO_CDR_OP_Xyz_SeqOfAStruct_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfAStruct &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfAStruct &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfAStruct_H_ */

// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Xyz::ArrayOfAStruct_forany &_tao_array);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::ArrayOfAStruct_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructContainingArrayOfAStruct &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructContainingArrayOfAStruct &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_union/cdr_op_ch.cpp:41


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::AUnion &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::AUnion &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_union/cdr_op_ch.cpp:41


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::BigUnion &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::BigUnion &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructAUnion &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructAUnion &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_SeqOfAUnion_H_
#define _TAO_CDR_OP_Xyz_SeqOfAUnion_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::SeqOfAUnion &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::SeqOfAUnion &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_SeqOfAUnion_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_AStructSeq_H_
#define _TAO_CDR_OP_Xyz_AStructSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::AStructSeq &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::AStructSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_AStructSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Xyz::ArrayOfAStructSeq_forany &_tao_array);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::ArrayOfAStructSeq_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::StructContainingArrayOfAStructSeq &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::StructContainingArrayOfAStructSeq &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_Xyz_BigUnionSeq_H_
#define _TAO_CDR_OP_Xyz_BigUnionSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


FooLib_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Xyz::BigUnionSeq &_tao_sequence);
FooLib_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Xyz::BigUnionSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Xyz_BigUnionSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Xyz::OctetArray_forany &_tao_array);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::OctetArray_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

FooLib_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Xyz::Foo &);
FooLib_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Xyz::Foo &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "FooDefC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

