/**
 * @file Test.idl
 *
 * $Id: Test.idl 14 2007-02-01 15:49:12Z mitza $
 *
 * @author Carlos O'Ryan <coryan@atdesk.com>
 *
 */
#ifndef Test__idl_
#define Test__idl_

module Test
{
  typedef sequence<octet> Payload;
  interface Peer
  {
    oneway void callme (in Peer callback,
                        in unsigned long max_depth,
                        in Payload extra_data);

    oneway void crash();

    void noop();
  };
};

#endif /* Test__idl_ */
