// -*- IDL -*-

//=============================================================================
/**
 * @file   ObjectReferenceFactory.idl
 *
 * $Id: ObjectReferenceFactory.idl 14 2007-02-01 15:49:12Z mitza $
 *
 * @author Ossama Othman <ossama@uci.edu>
 */
//=============================================================================


#ifndef OBJECT_REFERENCE_FACTORY_IDL
#define OBJECT_REFERENCE_FACTORY_IDL

#include "tao/ObjRefTemplate/ObjectReferenceTemplate_include.pidl"

module ORT_Test
{

  valuetype ObjectReferenceFactory
    : PortableInterceptor::ObjectReferenceFactory {};

};

#endif  /* OBJECT_REFERENCE_FACTORY_IDL */
