// $Id: Base.idl 2179 2013-05-28 22:16:51Z mesnierp $
#ifndef BASE_IDL_
#define BASE_IDL_

#pragma ciao lem "Coll_Base/BaseE.idl"

struct pointer_id
  {
    long point;
    string txt;
  };

// Interfaces for communication between Sender and Receiver
interface Hello {
  void set_point(in pointer_id p, in string strategy);
 };


#endif /* BASE_IDL_ */
