//
// $Id: Test.idl 14 2007-02-01 15:49:12Z mitza $

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  /// A very simple interface
  interface Simple
  {
    /// Return a simple string
    string get_string ();

  };
};

