// $Id: TSEC_CheckPointEI.idl 1861 2011-08-31 16:18:08Z mesnierp $

#ifndef TSEC_CHECKPOINTEI_IDL
#define TSEC_CHECKPOINTEI_IDL

#include "TSEC_CheckPoint.idl"

module ENW
{
  local interface TSEC_CheckPoint_Exec :
         CCM_TSEC_CheckPoint,
         CCM_ISessionService,
         Components::SessionComponent
  {
  };
};

#endif /* TSEC_CHECKPOINTEI_IDL */
