//
// $Id: test.idl 14 2007-02-01 15:49:12Z mitza $
//

interface Test
{
  void test_method (in boolean client_propagated,
                    in short client_priority);

  oneway void shutdown ();
};
