// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p11
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_TESTMESSAGETYPESUPPORTC_KXKGLL_H_
#define _TAO_IDL_TESTMESSAGETYPESUPPORTC_KXKGLL_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "testMessageC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace profilingTest
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< profilingTest::testMsg, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> testMsgSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_PROFILINGTEST_TESTMSGTYPESUPPORT__VAR_OUT_CH_)
#define _PROFILINGTEST_TESTMSGTYPESUPPORT__VAR_OUT_CH_

  class testMsgTypeSupport;
  typedef testMsgTypeSupport *testMsgTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        testMsgTypeSupport
      >
    testMsgTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        testMsgTypeSupport
      >
    testMsgTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  testMsgTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef testMsgTypeSupport_ptr _ptr_type;
    typedef testMsgTypeSupport_var _var_type;
    typedef testMsgTypeSupport_out _out_type;

    // The static operations.
    static testMsgTypeSupport_ptr _duplicate (testMsgTypeSupport_ptr obj);

    static void _tao_release (testMsgTypeSupport_ptr obj);

    static testMsgTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static testMsgTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static testMsgTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    testMsgTypeSupport (void);

    

    virtual ~testMsgTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    testMsgTypeSupport (const testMsgTypeSupport &);

    void operator= (const testMsgTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_PROFILINGTEST_TESTMSGDATAWRITER__VAR_OUT_CH_)
#define _PROFILINGTEST_TESTMSGDATAWRITER__VAR_OUT_CH_

  class testMsgDataWriter;
  typedef testMsgDataWriter *testMsgDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        testMsgDataWriter
      >
    testMsgDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        testMsgDataWriter
      >
    testMsgDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  testMsgDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef testMsgDataWriter_ptr _ptr_type;
    typedef testMsgDataWriter_var _var_type;
    typedef testMsgDataWriter_out _out_type;

    // The static operations.
    static testMsgDataWriter_ptr _duplicate (testMsgDataWriter_ptr obj);

    static void _tao_release (testMsgDataWriter_ptr obj);

    static testMsgDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static testMsgDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static testMsgDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::profilingTest::testMsg & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::profilingTest::testMsg & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::profilingTest::testMsg & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::profilingTest::testMsg & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::profilingTest::testMsg & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::profilingTest::testMsg & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::profilingTest::testMsg & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::profilingTest::testMsg & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::profilingTest::testMsg & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::profilingTest::testMsg & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    testMsgDataWriter (void);

    

    virtual ~testMsgDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    testMsgDataWriter (const testMsgDataWriter &);

    void operator= (const testMsgDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_PROFILINGTEST_TESTMSGDATAREADER__VAR_OUT_CH_)
#define _PROFILINGTEST_TESTMSGDATAREADER__VAR_OUT_CH_

  class testMsgDataReader;
  typedef testMsgDataReader *testMsgDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        testMsgDataReader
      >
    testMsgDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        testMsgDataReader
      >
    testMsgDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  testMsgDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef testMsgDataReader_ptr _ptr_type;
    typedef testMsgDataReader_var _var_type;
    typedef testMsgDataReader_out _out_type;

    // The static operations.
    static testMsgDataReader_ptr _duplicate (testMsgDataReader_ptr obj);

    static void _tao_release (testMsgDataReader_ptr obj);

    static testMsgDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static testMsgDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static testMsgDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::profilingTest::testMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::profilingTest::testMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::profilingTest::testMsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::profilingTest::testMsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::profilingTest::testMsg & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::profilingTest::testMsg & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::profilingTest::testMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::profilingTest::testMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::profilingTest::testMsgSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::profilingTest::testMsgSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::profilingTest::testMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::profilingTest::testMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::profilingTest::testMsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::profilingTest::testMsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::profilingTest::testMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::profilingTest::testMsg & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::profilingTest::testMsg & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    testMsgDataReader (void);

    

    virtual ~testMsgDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    testMsgDataReader (const testMsgDataReader &);

    void operator= (const testMsgDataReader &);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module profilingTest

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_PROFILINGTEST_TESTMSGTYPESUPPORT__TRAITS_)
#define _PROFILINGTEST_TESTMSGTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::profilingTest::testMsgTypeSupport>
  {
    static ::profilingTest::testMsgTypeSupport_ptr duplicate (
        ::profilingTest::testMsgTypeSupport_ptr p);
    static void release (
        ::profilingTest::testMsgTypeSupport_ptr p);
    static ::profilingTest::testMsgTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::profilingTest::testMsgTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_PROFILINGTEST_TESTMSGDATAWRITER__TRAITS_)
#define _PROFILINGTEST_TESTMSGDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::profilingTest::testMsgDataWriter>
  {
    static ::profilingTest::testMsgDataWriter_ptr duplicate (
        ::profilingTest::testMsgDataWriter_ptr p);
    static void release (
        ::profilingTest::testMsgDataWriter_ptr p);
    static ::profilingTest::testMsgDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::profilingTest::testMsgDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_PROFILINGTEST_TESTMSGDATAREADER__TRAITS_)
#define _PROFILINGTEST_TESTMSGDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::profilingTest::testMsgDataReader>
  {
    static ::profilingTest::testMsgDataReader_ptr duplicate (
        ::profilingTest::testMsgDataReader_ptr p);
    static void release (
        ::profilingTest::testMsgDataReader_ptr p);
    static ::profilingTest::testMsgDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::profilingTest::testMsgDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "testMessageTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

