//
// $Id: test.idl 14 2007-02-01 15:49:12Z mitza $
//


interface test
{
  void normal_method ();
  void unknown_exception_in_method ();
  void unknown_exception_during_deactivation ();
};

interface test_factory
{
  test create_test ();
  void shutdown ();
};

