// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p11
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_TESTTYPESUPPORTC_WFD9IN_H_
#define _TAO_IDL_TESTTYPESUPPORTC_WFD9IN_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "Priority_export.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "TestC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO Priority_Export

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace Test
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Test::Data, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> DataSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_TEST_DATATYPESUPPORT__VAR_OUT_CH_)
#define _TEST_DATATYPESUPPORT__VAR_OUT_CH_

  class DataTypeSupport;
  typedef DataTypeSupport *DataTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        DataTypeSupport
      >
    DataTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        DataTypeSupport
      >
    DataTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class Priority_Export DataTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef DataTypeSupport_ptr _ptr_type;
    typedef DataTypeSupport_var _var_type;
    typedef DataTypeSupport_out _out_type;

    // The static operations.
    static DataTypeSupport_ptr _duplicate (DataTypeSupport_ptr obj);

    static void _tao_release (DataTypeSupport_ptr obj);

    static DataTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static DataTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DataTypeSupport (void);

    

    virtual ~DataTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataTypeSupport (const DataTypeSupport &);

    void operator= (const DataTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_TEST_DATADATAWRITER__VAR_OUT_CH_)
#define _TEST_DATADATAWRITER__VAR_OUT_CH_

  class DataDataWriter;
  typedef DataDataWriter *DataDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        DataDataWriter
      >
    DataDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        DataDataWriter
      >
    DataDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class Priority_Export DataDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef DataDataWriter_ptr _ptr_type;
    typedef DataDataWriter_var _var_type;
    typedef DataDataWriter_out _out_type;

    // The static operations.
    static DataDataWriter_ptr _duplicate (DataDataWriter_ptr obj);

    static void _tao_release (DataDataWriter_ptr obj);

    static DataDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static DataDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Test::Data & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Test::Data & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Test::Data & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Test::Data & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Test::Data & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Test::Data & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Test::Data & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Test::Data & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Test::Data & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Test::Data & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DataDataWriter (void);

    

    virtual ~DataDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataDataWriter (const DataDataWriter &);

    void operator= (const DataDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_TEST_DATADATAREADER__VAR_OUT_CH_)
#define _TEST_DATADATAREADER__VAR_OUT_CH_

  class DataDataReader;
  typedef DataDataReader *DataDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        DataDataReader
      >
    DataDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        DataDataReader
      >
    DataDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class Priority_Export DataDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef DataDataReader_ptr _ptr_type;
    typedef DataDataReader_var _var_type;
    typedef DataDataReader_out _out_type;

    // The static operations.
    static DataDataReader_ptr _duplicate (DataDataReader_ptr obj);

    static void _tao_release (DataDataReader_ptr obj);

    static DataDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static DataDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Test::DataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Test::DataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Test::DataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Test::DataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Test::Data & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Test::Data & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Test::DataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Test::DataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Test::DataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Test::DataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Test::DataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Test::DataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Test::DataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Test::DataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Test::DataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Test::Data & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Test::Data & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DataDataReader (void);

    

    virtual ~DataDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataDataReader (const DataDataReader &);

    void operator= (const DataDataReader &);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module Test

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_TEST_DATATYPESUPPORT__TRAITS_)
#define _TEST_DATATYPESUPPORT__TRAITS_

  template<>
  struct Priority_Export Objref_Traits< ::Test::DataTypeSupport>
  {
    static ::Test::DataTypeSupport_ptr duplicate (
        ::Test::DataTypeSupport_ptr p);
    static void release (
        ::Test::DataTypeSupport_ptr p);
    static ::Test::DataTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Test::DataTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_TEST_DATADATAWRITER__TRAITS_)
#define _TEST_DATADATAWRITER__TRAITS_

  template<>
  struct Priority_Export Objref_Traits< ::Test::DataDataWriter>
  {
    static ::Test::DataDataWriter_ptr duplicate (
        ::Test::DataDataWriter_ptr p);
    static void release (
        ::Test::DataDataWriter_ptr p);
    static ::Test::DataDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Test::DataDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_TEST_DATADATAREADER__TRAITS_)
#define _TEST_DATADATAREADER__TRAITS_

  template<>
  struct Priority_Export Objref_Traits< ::Test::DataDataReader>
  {
    static ::Test::DataDataReader_ptr duplicate (
        ::Test::DataDataReader_ptr p);
    static void release (
        ::Test::DataDataReader_ptr p);
    static ::Test::DataDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Test::DataDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "TestTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

