//
// $Id: Test.idl 14 2007-02-01 15:49:12Z mitza $
//

module Test
{
  interface HelloWorld
  {
    string get_string ();
  };

  interface Hello
  {
    HelloWorld  get_helloworld ();

    oneway void shutdown ();
  };
};
