/**
 * @file Test.idl
 *
 * $Id: Test.idl 1861 2011-08-31 16:18:08Z mesnierp $
 *
 */

module Test
{
   typedef string<10> MyString;
   typedef MyString OtherString;

   interface Foo
   {
      void op1( in MyString s );
      void op2( in OtherString s );
   };
};

