// $Id: common.h 2179 2013-05-28 22:16:51Z mesnierp $

#define CLIENT_COMPRESSION_LEVEL 7
#define SERVER_COMPRESSION_LEVEL 5
#define LEAST_COMPRESSION_LEVEL ((CLIENT_COMPRESSION_LEVEL < SERVER_COMPRESSION_LEVEL) ?\
                                  CLIENT_COMPRESSION_LEVEL : SERVER_COMPRESSION_LEVEL)

#define DEFAULT_IOR_FILENAME ACE_TEXT("test.ior");
static int test = 1;
